-- The office's collaborator and agreement lists, as reference data.
--
-- Seeded from "Q bridge_List of Collaborators & Agreements.xlsx", which the
-- Research Office maintains: 328 counterparties with their countries, and
-- 51 agreement types. The workbook lives on a desktop and this migration runs
-- on a server, so the rows are literals rather than a file read.
--
-- The counterparty list mixes organisations and named individuals. Both are
-- seeded as institutions: the field they fill in is "who is the agreement
-- with", and for a consultancy that is a person. Guessing which is which would
-- drop real counterparties on a distinction the form does not make.
--
-- Reaches production through docker-entrypoint.sh.

-- ── Countries on institutions ───────────────────────────────────────────────
-- Recorded so a contract naming a counterparty can fill in its country rather
-- than asking somebody to type it again. Nullable: the office's list has one
-- for every row today, but a counterparty added through the form has none
-- until somebody says.
ALTER TABLE "institutions"
  ADD COLUMN IF NOT EXISTS "country" text;

-- ── The counterparties ──────────────────────────────────────────────────────
-- name_key carries the unique index, so a name already present under another
-- spelling is not duplicated. Where a row already exists without a country,
-- take the one from the office's list; never overwrite a country already there.
INSERT INTO "institutions" ("name", "name_key", "country") VALUES
  ('10 Genomics', '10genomics', 'United States'),
  ('Abeer Fadda', 'abeerfadda', 'Qatar'),
  ('Acumenta', 'acumenta', 'United States'),
  ('Addgene', 'addgene', 'United States'),
  ('AEONS-USA', 'aeonsusa', 'United States'),
  ('Age Khan University Hospital', 'agekhanuniversityhospital', 'Pakistan'),
  ('Ahmed Seri Ibrahim Mohamed', 'ahmedseriibrahimmohamed', 'Qatar'),
  ('Aisthesis', 'aisthesis', 'Qatar'),
  ('Al Gannas', 'algannas', 'Qatar'),
  ('Alborz University', 'alborzuniversity', 'Iran'),
  ('Alexion', 'alexion', 'United States'),
  ('Aljoud Nasser Almerri', 'aljoudnasseralmerri', 'Qatar'),
  ('American Type Culture Collection (ATCC)', 'americantypeculturecollectionatcc', 'United States'),
  ('American University of Beirut', 'americanuniversityofbeirut', 'Lebanon'),
  ('Amplifier Health Inc', 'amplifierhealthinc', 'United States'),
  ('Amryt Pharmaceuticals', 'amrytpharmaceuticals', 'Ireland'),
  ('Anti-Doping Laboratory', 'antidopinglaboratory', 'Qatar'),
  ('Applied Biological Materials', 'appliedbiologicalmaterials', 'Canada'),
  ('Applied Biological Materials (ABM)', 'appliedbiologicalmaterialsabm', 'Canada'),
  ('Arbor Biotechnologies', 'arborbiotechnologies', 'United States'),
  ('Arbor Technologies', 'arbortechnologies', 'United States'),
  ('Argus Cognitive', 'arguscognitive', 'United States'),
  ('ASSISTANCE PUBLIQUE - HÔPITAUX DE PARIS'' ("APHP")', 'assistancepubliquehpitauxdeparisaphp', 'France'),
  ('Asst Grande Ospedale Metropolitano Niguarda', 'asstgrandeospedalemetropolitanoniguarda', 'Italy'),
  ('Autism Speaks Inc. (AS)', 'autismspeaksincas', 'United States'),
  ('AVANOS', 'avanos', 'United States'),
  ('Avellino Lab', 'avellinolab', 'United States'),
  ('Aysenur ugur - Konya City Hospital', 'aysenurugurkonyacityhospital', 'Turkey'),
  ('Azienda Sanitaria Dell''Alto Adige - ASDAA (Formerly Bolzano General Hospital)', 'aziendasanitariadellaltoadigeasdaaformerlybolzanogeneralhospital', 'Italy'),
  ('Barcelona institute for global health', 'barcelonainstituteforglobalhealth', 'Spain'),
  ('Barcelona Supercomputing Center, Spain', 'barcelonasupercomputingcenterspain', 'Spain'),
  ('Baylor College of Medicine', 'baylorcollegeofmedicine', 'United States'),
  ('BC Children''s Hospital, Vancouver, Canada', 'bcchildrenshospitalvancouvercanada', 'Canada'),
  ('Beckman Coulter', 'beckmancoulter', 'United States'),
  ('Beijing Deepwise & League of PHD Technology Co', 'beijingdeepwiseleagueofphdtechnologyco', 'China'),
  ('Benovolent AI', 'benovolentai', 'United Kingdom'),
  ('BiKrysal Inc.', 'bikrysalinc', 'Canada'),
  ('Bilkent University', 'bilkentuniversity', 'Turkey'),
  ('Bio4Dreams S.p.A', 'bio4dreamsspa', 'Italy'),
  ('Biogen Idec Research Limited', 'biogenidecresearchlimited', 'United Kingdom'),
  ('Bionano Genomics Inc.', 'bionanogenomicsinc', 'United States'),
  ('Bionl, Inc', 'bionlinc', 'United States'),
  ('Bioptimus SAS', 'bioptimussas', 'France'),
  ('BioSensics LLC', 'biosensicsllc', 'United States'),
  ('BlueSavant AI', 'bluesavantai', 'United States'),
  ('Bolzano General Hospital', 'bolzanogeneralhospital', 'Italy'),
  ('Bolzano,Pavia,Niguarda,Fred Huch', 'bolzanopavianiguardafredhuch', 'United States'),
  ('Brigham and Women''s Hospital', 'brighamandwomenshospital', 'United States'),
  ('CAMBRIDGE UNIVERSITY HOSPITALS NHS FOUNDATION TRUST', 'cambridgeuniversityhospitalsnhsfoundationtrust', 'United Kingdom'),
  ('Caring Cross Inc', 'caringcrossinc', 'United States'),
  ('Caris MPI', 'carismpi', 'United States'),
  ('Carls Zeiss Microscopy GmbH', 'carlszeissmicroscopygmbh', 'Germany'),
  ('Carnegie Mellon University', 'carnegiemellonuniversity', 'Qatar'),
  ('Catholic University of the Sacred Heart of Rome', 'catholicuniversityofthesacredheartofrome', 'Italy'),
  ('Centre Hospitalier de iUniversite de Montreal (CHUM)', 'centrehospitalierdeiuniversitedemontrealchum', 'Canada'),
  ('Centre Hospitalier de l''Université de Montréal', 'centrehospitalierdeluniversitdemontral', 'Canada'),
  ('Centre Hospitalier Universitaire De La Reunion', 'centrehospitalieruniversitairedelareunion', 'France'),
  ('Centre Hospitalier Universitaire Sainte-Justine', 'centrehospitalieruniversitairesaintejustine', 'Canada'),
  ('Certara', 'certara', 'United States'),
  ('Children Hospital of Philadelphia', 'childrenhospitalofphiladelphia', 'United States'),
  ('Children''s Welfare Teaching Hospital', 'childrenswelfareteachinghospital', 'Iraq'),
  ('CIGGI Consortium', 'ciggiconsortium', NULL),
  ('Cincinnati Children''s Hospital Medical Center', 'cincinnatichildrenshospitalmedicalcenter', 'United States'),
  ('Clinical Biosamples & Research Services (CBRS)', 'clinicalbiosamplesresearchservicescbrs', 'India'),
  ('Cliniques Universitaires Saint-Luc (CUSL)', 'cliniquesuniversitairessaintluccusl', 'Belgium'),
  ('Clintec International FZ-LLC', 'clintecinternationalfzllc', 'United Arab Emirates'),
  ('CNR - National Research Council', 'cnrnationalresearchcouncil', 'Italy'),
  ('COMSATS University Islamabad, Abbottabad Campus', 'comsatsuniversityislamabadabbottabadcampus', 'Pakistan'),
  ('Corell', 'corell', 'United States'),
  ('Coriell Institute for Medical Research', 'coriellinstituteformedicalresearch', 'United States'),
  ('Cristina Maccalli', 'cristinamaccalli', 'Italy'),
  ('Cytori Therapeutics', 'cytoritherapeutics', 'Japan'),
  ('Dasman Diabetes Institute', 'dasmandiabetesinstitute', 'Kuwait'),
  ('Deerfield Doha LLC - QFC Branch', 'deerfielddohallcqfcbranch', 'Qatar'),
  ('Deutsches Krebsforchungezentrum (DKFZ)', 'deutscheskrebsforchungezentrumdkfz', 'Germany'),
  ('Dexus', 'dexus', 'Spain'),
  ('DIfE, Potsdam, Germany', 'difepotsdamgermany', 'Germany'),
  ('DLOC Biosystems Limited', 'dlocbiosystemslimited', 'United Kingdom'),
  ('DNAstack', 'dnastack', 'Canada'),
  ('Doha Institute of Graduate Studies', 'dohainstituteofgraduatestudies', 'Qatar'),
  ('DOKUZ EYLUL UNIVERSITY INSTITUTE OF ONCOLOGY', 'dokuzeyluluniversityinstituteofoncology', 'Turkey'),
  ('Droobi LLC', 'droobillc', 'Qatar'),
  ('Duke University', 'dukeuniversity', 'United States'),
  ('Ebn Sina Medical', 'ebnsinamedical', 'Qatar'),
  ('ECOG-ACRIN Cancer Research Group', 'ecogacrincancerresearchgroup', 'United States'),
  ('Equine Veterinary Medical Center (EVMC)', 'equineveterinarymedicalcenterevmc', 'Qatar'),
  ('Equine Veterinary Medical Centre (EVMC)', 'equineveterinarymedicalcentreevmc', 'Qatar'),
  ('Erasmus University Rotterdam', 'erasmusuniversityrotterdam', 'Netherlands'),
  ('Établissement français du sang, Franc', 'tablissementfranaisdusangfranc', 'France'),
  ('European Zebrafish Resource Center (EZRC)', 'europeanzebrafishresourcecenterezrc', 'Germany'),
  ('F. Hoffmann-La Roche Ltd', 'fhoffmannlarocheltd', 'Switzerland'),
  ('FABRIC GENOMICS', 'fabricgenomics', 'United States'),
  ('Farook Al Ajli', 'farookalajli', 'Qatar'),
  ('Fondazione IRCCS Istituto Nazionale dei Tumori', 'fondazioneirccsistitutonazionaledeitumori', 'Italy'),
  ('Fondazione IRCCS Policinico San Matto', 'fondazioneirccspolicinicosanmatto', 'Italy'),
  ('Fred Hutchinson Cancer Research Center', 'fredhutchinsoncancerresearchcenter', 'United States'),
  ('G+FLAS Life Sciences', 'gflaslifesciences', 'South Korea'),
  ('Genetech,Inc.', 'genetechinc', 'United States'),
  ('Genialis Inc', 'genialisinc', 'United States'),
  ('Genomics England Limited', 'genomicsenglandlimited', 'United Kingdom'),
  ('GLAXOSMITHKLINE BIOLOGICAL', 'glaxosmithklinebiological', 'Belgium'),
  ('Glencoe Software, Inc.', 'glencoesoftwareinc', 'United States'),
  ('Hamad Bin Khalifa University (HBKU)', 'hamadbinkhalifauniversityhbku', 'Qatar'),
  ('Hamad Medical Corporation (HMC)', 'hamadmedicalcorporationhmc', 'Qatar'),
  ('Hamilton Bonaduz', 'hamiltonbonaduz', 'Switzerland'),
  ('Harvard Medical School', 'harvardmedicalschool', 'United States'),
  ('Hattepe University', 'hattepeuniversity', 'Turkey'),
  ('Health Tech LLC', 'healthtechllc', 'Qatar'),
  ('Healthlytics AI LLC', 'healthlyticsaillc', 'Qatar'),
  ('Helmholtz Center, Munich, Germany', 'helmholtzcentermunichgermany', 'Germany'),
  ('Hibiscus Capital Management', 'hibiscuscapitalmanagement', 'United States'),
  ('Hospital for Sick Children', 'hospitalforsickchildren', 'Canada'),
  ('Hospital Sant Joan De Deu - HSJD', 'hospitalsantjoandedeuhsjd', 'Spain'),
  ('Human Cell Design', 'humancelldesign', 'France'),
  ('Icahn School of Medicine at Mount Sinai', 'icahnschoolofmedicineatmountsinai', 'United States'),
  ('Idea Elan LLC', 'ideaelanllc', 'Qatar'),
  ('Idibell', 'idibell', 'Spain'),
  ('Igeloxos Consulting Ltd', 'igeloxosconsultingltd', 'Cyprus'),
  ('Ignite Sweden SWE AB', 'igniteswedensweab', 'Sweden'),
  ('Illumina', 'illumina', 'United Kingdom'),
  ('ImproveCareNOW, Inc', 'improvecarenowinc', 'United States'),
  ('Inserm', 'inserm', 'France'),
  ('Institiuto Gulbenkian de Ciência', 'institiutogulbenkiandecincia', 'Portugal'),
  ('Institut Agronomique Et Vétérinaire Hassan II- Sub Awardee', 'institutagronomiqueetvtrinairehassaniisubawardee', 'Morocco'),
  ('Institut national de la santé et de la recherche médicale (INSERM)', 'institutnationaldelasantetdelarecherchemdicaleinserm', 'France'),
  ('Institut Paoli-Calmettes', 'institutpaolicalmettes', 'France'),
  ('Institute of Maternal and Child research (IDIMI), Faculty of Medicine, University of Chile and Hospital San Borja Arriaran', 'instituteofmaternalandchildresearchidimifacultyofmedicineuniversityofchileandhospitalsanborjaarriaran', 'Chile'),
  ('Institute of Molecular and Cell Biology (IMCB)', 'instituteofmolecularandcellbiologyimcb', 'Singapore'),
  ('Instituto Nazionales Tumori, IRCCS Fondazione Pascale, Napoli', 'institutonazionalestumoriirccsfondazionepascalenapoli', 'Italy'),
  ('IQSEC2 Research and Advocacy Foundation', 'iqsec2researchandadvocacyfoundation', 'United States'),
  ('IQVIA AG', 'iqviaag', 'Switzerland'),
  ('IQVIA Inc.', 'iqviainc', 'United States'),
  ('IQVIA RDS Egypt LLC', 'iqviardsegyptllc', 'Egypt'),
  ('IRB Barcelona', 'irbbarcelona', 'Spain'),
  ('IS Global', 'isglobal', 'Spain'),
  ('Istanbul Ticaret University', 'istanbulticaretuniversity', 'Turkey'),
  ('IZMIR Biomedicine and Genome Center', 'izmirbiomedicineandgenomecenter', 'Turkey'),
  ('JDRF', 'jdrf', 'United States'),
  ('Karolinska', 'karolinska', 'Sweden'),
  ('Katara', 'katara', 'Qatar'),
  ('King Abdulaziz University Hospital', 'kingabdulazizuniversityhospital', 'Saudi Arabia'),
  ('King Fahad Medical City', 'kingfahadmedicalcity', 'Saudi Arabia'),
  ('King Faisal Specialist Hospital and Research Center', 'kingfaisalspecialisthospitalandresearchcenter', 'Saudi Arabia'),
  ('King Hussein Cancer Center (KHCC)', 'kinghusseincancercenterkhcc', 'Jordan'),
  ('King''s College London', 'kingscollegelondon', 'United Kingdom'),
  ('Kite Pharma', 'kitepharma', 'United States'),
  ('Korean Collection for type cultures(KCTC),Microbial Resource Center', 'koreancollectionfortypecultureskctcmicrobialresourcecenter', 'South Korea'),
  ('Kuwait Medical Genetics Center', 'kuwaitmedicalgeneticscenter', 'Kuwait'),
  ('Kuwait University', 'kuwaituniversity', 'Kuwait'),
  ('L.E.K Consulting LLC', 'lekconsultingllc', 'United States'),
  ('La Jolla Institute', 'lajollainstitute', 'United States'),
  ('LabVantage Solutions, Ltd', 'labvantagesolutionsltd', 'Cyprus'),
  ('Lant Medical Ltd', 'lantmedicalltd', 'United Kingdom'),
  ('Lawson Health Research Institute', 'lawsonhealthresearchinstitute', 'Canada'),
  ('Leiden University Medical Center (LUMC)', 'leidenuniversitymedicalcenterlumc', 'Netherlands'),
  ('Limula SA', 'limulasa', 'Switzerland'),
  ('LOREM VASCULAR PTE. LTD', 'loremvascularpteltd', 'Singapore'),
  ('Luminary Therapeutics', 'luminarytherapeutics', 'Qatar'),
  ('Maastricht University Medical Centre', 'maastrichtuniversitymedicalcentre', 'Netherlands'),
  ('Mahidol University', 'mahidoluniversity', 'Thailand'),
  ('Marmara University', 'marmarauniversity', 'Turkey'),
  ('Martin Luther University of Halle-Wittenberg', 'martinlutheruniversityofhallewittenberg', 'Germany'),
  ('Mas Holding', 'masholding', 'Qatar'),
  ('Mavatar', 'mavatar', 'Sweden'),
  ('MBK HOLDING', 'mbkholding', 'Qatar'),
  ('McGill University', 'mcgilluniversity', 'Canada'),
  ('Medtronic Mediterranean S.A.L', 'medtronicmediterraneansal', 'Lebanon'),
  ('Medtronic META FZ-LLC', 'medtronicmetafzllc', 'United Arab Emirates'),
  ('Metabolon', 'metabolon', 'United States'),
  ('Microsoft Doha LLC', 'microsoftdohallc', 'Qatar'),
  ('Middle East Technical University', 'middleeasttechnicaluniversity', 'Turkey'),
  ('MILTENYI BIOTEC B.V.& CO. KG', 'miltenyibiotecbvcokg', 'Germany'),
  ('Ministry of Public Health - Qatar (MOPH)', 'ministryofpublichealthqatarmoph', 'Qatar'),
  ('MOHAMMED AMEEN AL-ALGHBAR', 'mohammedameenalalghbar', 'Qatar'),
  ('Monash University', 'monashuniversity', 'Australia'),
  ('Monell Chemical Senses Center in Philadelphia (USA)', 'monellchemicalsensescenterinphiladelphiausa', 'United States'),
  ('Murdoch Children''s Research Institute (MRCI)', 'murdochchildrensresearchinstitutemrci', 'Australia'),
  ('National Cancer Institute: Istituto Nazionale Tumori, Fondazione "G.Pascale", Streey Mariano Semmola snc. 80131, Napoli, Italy', 'nationalcancerinstituteistitutonazionaletumorifondazionegpascalestreeymarianosemmolasnc80131napoliitaly', 'Italy'),
  ('National Institute of Allergy and Infectious Diseases (NIAID)', 'nationalinstituteofallergyandinfectiousdiseasesniaid', 'United States'),
  ('National Institute of Genetics', 'nationalinstituteofgenetics', 'Japan'),
  ('National Institutes of Health (NIH)', 'nationalinstitutesofhealthnih', 'United States'),
  ('Neoteryx', 'neoteryx', 'United States'),
  ('New York University', 'newyorkuniversity', 'United States'),
  ('Newcastle University', 'newcastleuniversity', 'United Kingdom'),
  ('NextCode', 'nextcode', 'United States'),
  ('Nextsense S.r.l', 'nextsensesrl', 'Italy'),
  ('Nicholas Van Panhuys', 'nicholasvanpanhuys', 'New Zealand'),
  ('Northwestern University', 'northwesternuniversity', 'Qatar'),
  ('Nottingham Trent University', 'nottinghamtrentuniversity', 'United Kingdom'),
  ('Novartis Middle East FZE', 'novartismiddleeastfze', 'United Arab Emirates'),
  ('NuGO Association', 'nugoassociation', 'Netherlands'),
  ('Osaka University', 'osakauniversity', 'Japan'),
  ('Ospedale San Raffaele', 'ospedalesanraffaele', 'Italy'),
  ('Otsuka Pharmaceutical Development and Commercialization', 'otsukapharmaceuticaldevelopmentandcommercialization', 'United States'),
  ('Pacific Biosciences of California Inc. (PacBio)', 'pacificbiosciencesofcaliforniaincpacbio', 'United States'),
  ('Pacific North west Research Institute(PNRI)', 'pacificnorthwestresearchinstitutepnri', 'United States'),
  ('Palantir Technologies', 'palantirtechnologies', 'United Kingdom'),
  ('Plastic Sergi Centre', 'plasticsergicentre', 'Qatar'),
  ('Politecnico di Torino', 'politecnicoditorino', 'Italy'),
  ('Precision Life Ltd', 'precisionlifeltd', 'United Kingdom'),
  ('Primary Health Care Corporation (PHCC)', 'primaryhealthcarecorporationphcc', 'Qatar'),
  ('PsiQuantum Corp', 'psiquantumcorp', 'United States'),
  ('PTC Therapeutics International Ltd', 'ptctherapeuticsinternationalltd', 'Ireland'),
  ('Qatar Academy School', 'qataracademyschool', 'Qatar'),
  ('Qatar BioBank (QBB)', 'qatarbiobankqbb', 'Qatar'),
  ('Qatar Biomedical Research Institute (QBRI)', 'qatarbiomedicalresearchinstituteqbri', 'Qatar'),
  ('Qatar Computing Research Institute, (QCRI)', 'qatarcomputingresearchinstituteqcri', 'Qatar'),
  ('Qatar Foundation (QF)', 'qatarfoundationqf', 'Qatar'),
  ('Qatar International Islamic Bank', 'qatarinternationalislamicbank', 'Qatar'),
  ('Qatar Museums (Qatar Museums Authority)', 'qatarmuseumsqatarmuseumsauthority', 'Qatar'),
  ('Qatar National Research Fund (QNRF)', 'qatarnationalresearchfundqnrf', 'Qatar'),
  ('Qatar Precision Health Institute (QPHI)', 'qatarprecisionhealthinstituteqphi', 'Qatar'),
  ('Qatar Research Development and Innovation Council (QRDI)', 'qatarresearchdevelopmentandinnovationcouncilqrdi', 'Qatar'),
  ('Qatar University (QU', 'qataruniversityqu', 'Qatar'),
  ('QIAGEN', 'qiagen', 'Spain'),
  ('Qatar Cancer Society', 'qatarcancersociety', 'Qatar'),
  ('Quaid-i-Azam University', 'quaidiazamuniversity', 'Pakistan'),
  ('Quantinuum Ltd', 'quantinuumltd', 'United Kingdom'),
  ('Rady Children''s Hospital Research Center', 'radychildrenshospitalresearchcenter', 'United States'),
  ('Rani Therapeutics', 'ranitherapeutics', 'United States'),
  ('Razan Center for Infertility', 'razancenterforinfertility', 'Palestinian Territories'),
  ('Refugee Biotech', 'refugeebiotech', 'United States'),
  ('Rev.com', 'revcom', 'United States'),
  ('Rezolute Inc', 'rezoluteinc', 'United States'),
  ('Rhythm Pharmaceuticals', 'rhythmpharmaceuticals', 'Netherlands'),
  ('Rockefeller University', 'rockefelleruniversity', 'United States'),
  ('San Raffaele Hospital Scientific Institute', 'sanraffaelehospitalscientificinstitute', 'Italy'),
  ('ScaleReady LLC/Wilson Wolf Manufacturing LLC/Cell Ready LLC/Bio-Techne Corporation', 'scalereadyllcwilsonwolfmanufacturingllccellreadyllcbiotechnecorporation', NULL),
  ('ScaleReady/CellReady', 'scalereadycellready', 'United States'),
  ('Seattle Children''s Hospital DBA Seatlle Children''s Research Institute', 'seattlechildrenshospitaldbaseatllechildrensresearchinstitute', 'United States'),
  ('Semmelweis University', 'semmelweisuniversity', 'Hungary'),
  ('Shafllah Centre', 'shafllahcentre', 'Qatar'),
  ('Shanghai Fosun Kairos Biotechnology co. Ltd', 'shanghaifosunkairosbiotechnologycoltd', 'China'),
  ('Sidra Medicine', 'sidramedicine', 'Qatar'),
  ('SomaLogic Operating Co.Inc', 'somalogicoperatingcoinc', 'United States'),
  ('Spiral Genetics', 'spiralgenetics', 'United States'),
  ('Springer Nature Limited', 'springernaturelimited', 'United Kingdom'),
  ('Stanford University', 'stanforduniversity', 'United States'),
  ('Sultan Qaboos University Hospital', 'sultanqaboosuniversityhospital', 'Oman'),
  ('Taibah University', 'taibahuniversity', 'Saudi Arabia'),
  ('Tamo-Q', 'tamoq', 'Qatar'),
  ('TAN TOCK SENG HOSPITAL PTE LTD', 'tantocksenghospitalpteltd', 'Singapore'),
  ('TARN', 'tarn', 'United Kingdom'),
  ('Technologi Innovation Institute-Sole proprietorship LLC', 'technologiinnovationinstitutesoleproprietorshipllc', 'United Arab Emirates'),
  ('TechPreneur', 'techpreneur', 'Qatar'),
  ('Texas A&M Engineering Experiment Station on behalf of its division located at Texas A&M University at Qatar', 'texasamengineeringexperimentstationonbehalfofitsdivisionlocatedattexasamuniversityatqatar', 'Qatar'),
  ('Texas A&M University', 'texasamuniversity', 'Qatar'),
  ('The Aga Khan University', 'theagakhanuniversity', 'Pakistan'),
  ('The Children''s Hospital Corporation d/b/a Boston Children''s Hospital', 'thechildrenshospitalcorporationdbabostonchildrenshospital', 'United States'),
  ('The Children''s Hospital of Philadelphia (CHOP)', 'thechildrenshospitalofphiladelphiachop', 'United States'),
  ('The City University of New York', 'thecityuniversityofnewyork', 'United States'),
  ('The Cleveland Clinic Foundation', 'theclevelandclinicfoundation', 'United States'),
  ('The Cultural Village Foundation - Katara', 'theculturalvillagefoundationkatara', 'Qatar'),
  ('The Foundation for Liver Research', 'thefoundationforliverresearch', 'United Kingdom'),
  ('The General Hospital Corporation dba Massachusetts General Hospital', 'thegeneralhospitalcorporationdbamassachusettsgeneralhospital', 'United States'),
  ('The Government of the United Kingdom of Great Britain and Northern Ireland acting through the Foreign, Commonwealth & Development Office ("FCDO")', 'thegovernmentoftheunitedkingdomofgreatbritainandnorthernirelandactingthroughtheforeigncommonwealthdevelopmentofficefcdo', 'Qatar'),
  ('The Jakson Laboratory', 'thejaksonlaboratory', 'United States'),
  ('The Lebanese American University', 'thelebaneseamericanuniversity', 'Lebanon'),
  ('The Ministry of Commerce and Industry', 'theministryofcommerceandindustry', 'Qatar'),
  ('The University of Birmingham', 'theuniversityofbirmingham', 'United Kingdom'),
  ('The University of Minnesota', 'theuniversityofminnesota', 'United States'),
  ('The Westmead Institute for Medical Research', 'thewestmeadinstituteformedicalresearch', 'Australia'),
  ('Toro Bio', 'torobio', 'United States'),
  ('Travere Therapeutics', 'traveretherapeutics', 'Switzerland'),
  ('Traverse Health Europe B.V', 'traversehealtheuropebv', 'Netherlands'),
  ('TRUSTEES OF INDIANA UNIVERSITY ON BEHALF OF INDIANA UNIVERSITY SCHOOL OF MEDICINE', 'trusteesofindianauniversityonbehalfofindianauniversityschoolofmedicine', 'United States'),
  ('Tyrolean Cancer Research Institute', 'tyroleancancerresearchinstitute', 'Austria'),
  ('UK Biobank', 'ukbiobank', 'United Kingdom'),
  ('UMR INRAE UPPA', 'umrinraeuppa', 'France'),
  ('Universidade Federal do Rio Grande do Sul', 'universidadefederaldoriograndedosul', 'Brazil'),
  ('Università degli Studi del Sannio di Benevento]', 'universitdeglistudidelsanniodibenevento', 'Italy'),
  ('Università degli Studi di Milano', 'universitdeglistudidimilano', 'Italy'),
  ('Universitair Medisch Centrum Utrecht (UMC Utrecht)', 'universitairmedischcentrumutrechtumcutrecht', 'Netherlands'),
  ('Universitätsklinikum Tuebingen on behalf of Eberhard Karls Universitaet Tuebingen, Faculty of Medicine (EKUT) Institute of Medical Genetics and Applied Genomics', 'universittsklinikumtuebingenonbehalfofeberhardkarlsuniversitaettuebingenfacultyofmedicineekutinstituteofmedicalgeneticsandappliedgenomics', 'Germany'),
  ('Université Catholique de Louvain (UCL)', 'universitcatholiquedelouvainucl', 'Belgium'),
  ('University at Buffalo', 'universityatbuffalo', 'United States'),
  ('University Center of Health Sciences, University of Guadalaraja', 'universitycenterofhealthsciencesuniversityofguadalaraja', 'United States'),
  ('University College London', 'universitycollegelondon', 'United Kingdom'),
  ('University Hospital Düsseldorf (DDFG)', 'universityhospitaldsseldorfddfg', 'Germany'),
  ('University Hospital Ghent', 'universityhospitalghent', 'Belgium'),
  ('University of Aberdeen', 'universityofaberdeen', 'United Kingdom'),
  ('University of Athens', 'universityofathens', 'Greece'),
  ('University of Barcelona', 'universityofbarcelona', 'Spain'),
  ('University of Beira Interior', 'universityofbeirainterior', 'Portugal'),
  ('University of British Columbia', 'universityofbritishcolumbia', 'Canada'),
  ('University of Calgary', 'universityofcalgary', 'Qatar'),
  ('University of Cape Town', 'universityofcapetown', 'South Africa'),
  ('University of Cheiti', 'universityofcheiti', 'Italy'),
  ('University of Doha for Science and Technology', 'universityofdohaforscienceandtechnology', 'Qatar'),
  ('University of Exeter', 'universityofexeter', 'United Kingdom'),
  ('University of Florence', 'universityofflorence', 'Italy'),
  ('University of Genoa', 'universityofgenoa', 'Italy'),
  ('University of Iowa', 'universityofiowa', 'United States'),
  ('University of Melbourne', 'universityofmelbourne', 'Australia'),
  ('University of Miami', 'universityofmiami', 'United States'),
  ('University of Montreal (CHUM)', 'universityofmontrealchum', 'Canada'),
  ('University of Oxford', 'universityofoxford', 'United Kingdom'),
  ('University of Palermo', 'universityofpalermo', 'Italy'),
  ('University of Pennsylvania', 'universityofpennsylvania', 'United States'),
  ('University of Piemonte Orientale "Amedeo Avogadro"', 'universityofpiemonteorientaleamedeoavogadro', 'Italy'),
  ('University of Pittsburgh', 'universityofpittsburgh', 'United States'),
  ('University of Rome', 'universityofrome', 'Italy'),
  ('University of Rome Tor Vergata', 'universityofrometorvergata', 'Italy'),
  ('University of Sao Paulo', 'universityofsaopaulo', 'Brazil'),
  ('University of Sydney', 'universityofsydney', 'Australia'),
  ('University of Tasmania', 'universityoftasmania', 'Australia'),
  ('University of Texas, MD Anderson Cancer Center', 'universityoftexasmdandersoncancercenter', 'United States'),
  ('University of the Witwatersrand', 'universityofthewitwatersrand', 'South Africa'),
  ('University of Toronto', 'universityoftoronto', 'Canada'),
  ('University of Trestie', 'universityoftrestie', 'Italy'),
  ('University of Washington', 'universityofwashington', 'United States'),
  ('Uppsala University', 'uppsalauniversity', 'Sweden'),
  ('U-Smell-It LLC', 'usmellitllc', 'United States'),
  ('Vector Biomed,Inc', 'vectorbiomedinc', 'United States'),
  ('Venus MedTech Inc', 'venusmedtechinc', 'China'),
  ('Vertex Pharmaceuticals (Europe) Ltd', 'vertexpharmaceuticalseuropeltd', 'United Kingdom'),
  ('Vitafluence.ai GmbH', 'vitafluenceaigmbh', 'Germany'),
  ('Vitro Biopharma', 'vitrobiopharma', 'United States'),
  ('Wake Forest University Health Sciences', 'wakeforestuniversityhealthsciences', 'United States'),
  ('Watchmaker Genomics, Inc.', 'watchmakergenomicsinc', 'United States'),
  ('Weightless', 'weightless', 'United States'),
  ('Weill Cornell Medicine (WCM)', 'weillcornellmedicinewcm', 'Qatar'),
  ('Wiley', 'wiley', 'United States'),
  ('Wyne State Uni', 'wynestateuni', 'United States'),
  ('Yokohama Rosai Hospital', 'yokohamarosaihospital', 'Japan'),
  ('Zebrafish Center for Disease Modeling (ZCDM)', 'zebrafishcenterfordiseasemodelingzcdm', 'South Korea'),
  ('Zeclinics', 'zeclinics', 'Spain'),
  ('Zhejiang University', 'zhejianguniversity', 'China')
ON CONFLICT ("name_key") DO UPDATE
  SET "country" = COALESCE("institutions"."country", EXCLUDED."country"),
      "updated_at" = now();

-- ── Agreement types ─────────────────────────────────────────────────────────
-- Editable, for the same reason institutions are: the office knows its own
-- agreement vocabulary and should not need a deployment to extend it. The
-- eight the system shipped with are marked built-in and kept first, so
-- contracts already carrying one still have a type that is on the list.
CREATE TABLE IF NOT EXISTS "contract_types" (
  "id" serial PRIMARY KEY,
  "name" text NOT NULL,
  "name_key" text NOT NULL UNIQUE,
  "sort_order" integer NOT NULL DEFAULT 0,
  "is_built_in" boolean NOT NULL DEFAULT false,
  "created_by_user_id" integer REFERENCES "users"("id"),
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now()
);

INSERT INTO "contract_types" ("name", "name_key", "sort_order", "is_built_in") VALUES
  ('Collaboration', 'collaboration', 0, true),
  ('Service', 'service', 1, true),
  ('Material Transfer', 'materialtransfer', 2, true),
  ('Confidentiality', 'confidentiality', 3, true),
  ('License', 'license', 4, true),
  ('Other', 'other', 5, true),
  ('Consulting Agreement', 'consultingagreement', 6, true),
  ('Licensing Agreement', 'licensingagreement', 7, true),
  ('Amendment / Variation Agreement', 'amendmentvariationagreement', 8, false),
  ('Award Agreement / Notice of Award (NOA)', 'awardagreementnoticeofawardnoa', 9, false),
  ('Biobank Access Agreement', 'biobankaccessagreement', 10, false),
  ('Clinical Research Collaboration Agreement', 'clinicalresearchcollaborationagreement', 11, false),
  ('Clinical Site Agreement', 'clinicalsiteagreement', 12, false),
  ('Clinical Trial Agreement (CTA)', 'clinicaltrialagreementcta', 13, false),
  ('Co-Funding Agreement', 'cofundingagreement', 14, false),
  ('Collaborative Research Agreement (CRA)', 'collaborativeresearchagreementcra', 15, false),
  ('Confidentiality Agreement (CDA) / Non-Disclosure Agreement (NDA)', 'confidentialityagreementcdanondisclosureagreementnda', 16, false),
  ('Consultancy Agreement – Research', 'consultancyagreementresearch', 17, false),
  ('Cooperative Research and Development Agreement (CRADA)', 'cooperativeresearchanddevelopmentagreementcrada', 18, false),
  ('Cost Sharing Agreement (CSA)', 'costsharingagreementcsa', 19, false),
  ('Data Processing Agreement (DPA)', 'dataprocessingagreementdpa', 20, false),
  ('Data Transfer Agreement (DTA)', 'datatransferagreementdta', 21, false),
  ('Data Use Agreement (DUA)', 'datauseagreementdua', 22, false),
  ('Extension Agreement', 'extensionagreement', 23, false),
  ('Funding Agreement', 'fundingagreement', 24, false),
  ('Grant Agreement', 'grantagreement', 25, false),
  ('Human Biological Material Transfer Agreement', 'humanbiologicalmaterialtransferagreement', 26, false),
  ('In-Kind Contribution Agreement', 'inkindcontributionagreement', 27, false),
  ('Intellectual Property (IP) Agreement', 'intellectualpropertyipagreement', 28, false),
  ('Joint Intellectual Property Agreement', 'jointintellectualpropertyagreement', 29, false),
  ('Letter of Agreement (LoA)', 'letterofagreementloa', 30, false),
  ('Letter of Intent (LoI)', 'letterofintentloi', 31, false),
  ('License Agreement', 'licenseagreement', 32, false),
  ('Master Research Funding Agreement (MRFA)', 'masterresearchfundingagreementmrfa', 33, false),
  ('Material Transfer Agreement (MTA)', 'materialtransferagreementmta', 34, false),
  ('Memorandum of Agreement (MoA)', 'memorandumofagreementmoa', 35, false),
  ('Memorandum of Understanding (MoU)', 'memorandumofunderstandingmou', 36, false),
  ('No-Cost Extension Agreement', 'nocostextensionagreement', 37, false),
  ('Option Agreement', 'optionagreement', 38, false),
  ('Other Research Agreement / Contract', 'otherresearchagreementcontract', 39, false),
  ('Research Collaboration Agreement', 'researchcollaborationagreement', 40, false),
  ('Research Consortium Agreement', 'researchconsortiumagreement', 41, false),
  ('Research Fellowship Agreement', 'researchfellowshipagreement', 42, false),
  ('Research Resource Access Agreement', 'researchresourceaccessagreement', 43, false),
  ('Research Services Agreement (RSA)', 'researchservicesagreementrsa', 44, false),
  ('Service Level Agreement (SLA) – Research', 'servicelevelagreementslaresearch', 45, false),
  ('Site Agreement / Research Site Agreement', 'siteagreementresearchsiteagreement', 46, false),
  ('Sponsored Research Agreement (SRA)', 'sponsoredresearchagreementsra', 47, false),
  ('Sub-Award Agreement (SAA)', 'subawardagreementsaa', 48, false),
  ('Termination Agreement', 'terminationagreement', 49, false),
  ('Visiting Scientist / Researcher Agreement', 'visitingscientistresearcheragreement', 50, false)
ON CONFLICT ("name_key") DO NOTHING;
