-- Add all ibc_applications columns that exist in the Drizzle schema but may
-- be absent from the production database. Safe to re-run (IF NOT EXISTS).

ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS irbnet_ibc_number              text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS short_title                    text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS additional_notification_email  text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS biosafety_level                text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS risk_group_classification      text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS recombinant_synthetic_nucleic_acid      boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS whole_animals_animal_material           boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS animal_material_sub_options             json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS human_non_human_primate_material        boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS introducing_primate_material_into_animals boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS microorganisms_infectious_material      boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS introducing_recombinant_dna_to_microorganisms boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS biological_toxins                       boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS nanoparticles                           boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS arthropods                              boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS transgenic_arthropods_or_exposure       boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS plants                                  boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS transgenic_plants_or_exposure           boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS human_origin                            boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS human_materials                         text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS human_materials_tissues_other           text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS human_materials_other_material          text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS non_human_primate_origin                boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS nhp_exposure_kit                        boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS stem_cells                              text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS stem_cells_nih_registry                 boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS exposure_control_plan_compliance        boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS hand_washing_device                     boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS laundry_method                          text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS laundry_method_other                    text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS materials_contain_known_pathogens       boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS material_pathogen_details               text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS material_treatment_details              text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS infection_symptoms                      text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS biological_agents                       json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS chemical_agents                         json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS radiological_materials                  json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS recombinant_dna                         boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS animal_work                             boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS field_work                              boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS using_recombinant_dna_detection         boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS creating_genomic_libraries              boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS cloning_vector_construction             boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS expression_cultured_cells               boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS use_human_cell_lines                    boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS use_animal_cell_lines                   boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS use_stem_cells                          boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS risk_group_2_3_genes                    boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS administering_to_animals                boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS large_culture_volumes                   boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS infectious_virus_work                   boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS toxin_genes                             boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS approved_rooms                          json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS lab_policies_compliance                 json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS disinfection_methods                    json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS waste_sterilization_methods             json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS required_ppe                            json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS hazard_assessment                       json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS safety_controls                         json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS additional_recommended_controls         text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS iacuc_protocol_number                   text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS irb_protocol_number                     text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS medical_surveillance                    boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS vetted_date                             timestamp;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS under_review_date                       timestamp;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS last_review_date                        date;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS next_review_date                        date;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS workflow_status                         text DEFAULT 'draft';
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS submission_type                         text DEFAULT 'initial';
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS version                                 integer DEFAULT 1;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS risk_level                              text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS requires_monitoring                     boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS monitoring_frequency                    text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS reporting_requirements                  text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS reviewer_assignments                    json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS review_comments                         json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS pi_responses                            json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS protocol_team_members                   json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS description                             text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS protocol_summary                        text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS nih_section_abc                         text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS nih_section_d                           text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS nih_section_e                           text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS nih_section_f                           text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS nih_appendix_c                          text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS cell_lines                              json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS hazardous_procedures                    text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS synthetic_experiments                   text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS proposed_biosafety_levels               json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS host_organism_dna_propagation           text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS purification_measures                   text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS provided_restriction_vector_maps        boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS viral_genome_regions_altered            text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS assaying_wild_type_viral                boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS deviating_from_local_transport          boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS deviating_from_local_transport_details  text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS transporting_bio_hazardous_to_off_campus boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS transporting_bio_hazardous_to_off_campus_details text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS receiving_biological_from_off_campus    boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS dual_use_agents_and_toxins              boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS dual_use_categories_apply               boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS dual_use_categories_explanation         text;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS dual_use_experiment_categories          json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS handle_more_than_10_liters              boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS gene_drive_system_crispr                boolean DEFAULT false;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS form_data                               json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS inactivation_decontamination            json;
ALTER TABLE ibc_applications ADD COLUMN IF NOT EXISTS disposal                                json;
