-- AUTO-GENERATED by scripts/generate-sqlite-schema.ts — do not edit manually.
-- Re-generate after schema changes: npx tsx scripts/generate-sqlite-schema.ts
-- All statements use IF NOT EXISTS so this file is safe to re-run on startup.

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

-- branches
CREATE TABLE IF NOT EXISTS "branches" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "head_id" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- buildings
CREATE TABLE IF NOT EXISTS "buildings" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "name" TEXT NOT NULL,
  "address" TEXT,
  "description" TEXT,
  "totalFloors" INTEGER,
  "maxOccupancy" INTEGER,
  "emergencyContact" TEXT,
  "safetyNotes" TEXT
);

-- bulkDataArchives
CREATE TABLE IF NOT EXISTS "bulk_data_archives" (
  "id" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "source" TEXT NOT NULL,
  "schedule_date" TEXT,
  "file_name" TEXT,
  "object_id" TEXT,
  "byte_size" INTEGER,
  "checksum" TEXT,
  "lease_token" TEXT,
  "error_message" TEXT,
  "requested_by" TEXT,
  "created_at" TEXT NOT NULL,
  "started_at" TEXT,
  "completed_at" TEXT
);

-- certificationConfigurations
CREATE TABLE IF NOT EXISTS "certification_configurations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "institution_name" TEXT,
  "citi_api_key" TEXT,
  "citi_api_secret" TEXT,
  "citi_api_endpoint" TEXT,
  "notification_recipients" TEXT,
  "notification_days" TEXT,
  "email_enabled" INTEGER NOT NULL DEFAULT 1,
  "auto_import_enabled" INTEGER NOT NULL DEFAULT 0,
  "last_sync_date" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- certificationModules
CREATE TABLE IF NOT EXISTS "certification_modules" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "is_core" INTEGER NOT NULL DEFAULT 0,
  "expiration_months" INTEGER NOT NULL DEFAULT 36,
  "is_active" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- certifications
CREATE TABLE IF NOT EXISTS "certifications" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "scientist_id" INTEGER NOT NULL,
  "module_id" INTEGER NOT NULL,
  "start_date" TEXT NOT NULL,
  "end_date" TEXT NOT NULL,
  "certificate_file_path" TEXT,
  "certificate_file_name" TEXT,
  "report_file_path" TEXT,
  "report_file_name" TEXT,
  "extracted_data" TEXT,
  "uploaded_by" INTEGER NOT NULL,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- dataManagementPlans
CREATE TABLE IF NOT EXISTS "data_management_plans" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "research_activity_id" INTEGER NOT NULL,
  "dmp_number" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT,
  "data_collection_methods" TEXT,
  "data_storage_plan" TEXT,
  "data_sharing_plan" TEXT,
  "retention_period" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  CONSTRAINT "data_management_plans_dmp_number_unique" UNIQUE ("dmp_number")
);

-- departments
CREATE TABLE IF NOT EXISTS "departments" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "branch_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "head_id" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- featureRequests
CREATE TABLE IF NOT EXISTS "feature_requests" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "priority" TEXT NOT NULL DEFAULT 'medium',
  "category" TEXT NOT NULL DEFAULT 'feature',
  "original_request" TEXT NOT NULL,
  "enhanced_prompt" TEXT,
  "approved_prompt" TEXT,
  "ai_provider" TEXT,
  "implementation_notes" TEXT,
  "estimated_effort" TEXT,
  "tags" TEXT,
  "requested_by" TEXT NOT NULL DEFAULT 'Anonymous User',
  "upvotes" INTEGER NOT NULL DEFAULT 0,
  "upvoted_by" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- grantProgressReports
CREATE TABLE IF NOT EXISTS "grant_progress_reports" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "grant_id" INTEGER NOT NULL,
  "report_title" TEXT NOT NULL,
  "report_period" TEXT,
  "submission_date" TEXT,
  "acceptance_date" TEXT,
  "file_path" TEXT,
  "file_name" TEXT,
  "file_size" INTEGER,
  "uploaded_by" INTEGER NOT NULL,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- grantResearchActivities
CREATE TABLE IF NOT EXISTS "grant_research_activities" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "grant_id" INTEGER NOT NULL,
  "research_activity_id" INTEGER NOT NULL,
  "linked_date" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- grants
CREATE TABLE IF NOT EXISTS "grants" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "cycle" TEXT,
  "project_number" TEXT NOT NULL,
  "lpi_id" INTEGER,
  "investigator_type" TEXT,
  "title" TEXT NOT NULL,
  "requested_amount" REAL,
  "awarded_amount" REAL,
  "submitted_year" INTEGER,
  "awarded" INTEGER NOT NULL DEFAULT 0,
  "awarded_year" INTEGER,
  "running_time_years" INTEGER,
  "current_grant_year" TEXT,
  "status" TEXT NOT NULL DEFAULT 'submitted',
  "grant_type" TEXT DEFAULT 'Local',
  "source_category" TEXT,
  "source_record_key" TEXT,
  "submitting_institution" TEXT,
  "co_investigators" TEXT,
  "subaward_completed_year" INTEGER,
  "contribution_type" TEXT,
  "contribution_details" TEXT,
  "duration_months" INTEGER,
  "currency" TEXT,
  "start_date" TEXT,
  "end_date" TEXT,
  "reporting_interval_months" INTEGER,
  "collaborators" TEXT,
  "description" TEXT,
  "funding_agency" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  CONSTRAINT "grants_project_number_unique" UNIQUE ("project_number")
);

-- ibcApplicationComments
CREATE TABLE IF NOT EXISTS "ibc_application_comments" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "application_id" INTEGER NOT NULL,
  "comment_type" TEXT NOT NULL,
  "author_type" TEXT NOT NULL,
  "author_id" INTEGER,
  "author_name" TEXT NOT NULL,
  "comment" TEXT NOT NULL,
  "recommendation" TEXT,
  "status_from" TEXT,
  "status_to" TEXT,
  "is_internal" INTEGER DEFAULT 0,
  "created_at" TEXT
);

-- ibcApplicationPpe
CREATE TABLE IF NOT EXISTS "ibc_application_ppe" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "application_id" INTEGER NOT NULL,
  "room_id" INTEGER NOT NULL,
  "ppe_item" TEXT NOT NULL,
  "created_at" TEXT
);

-- ibcApplicationResearchActivities
CREATE TABLE IF NOT EXISTS "ibc_application_research_activities" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "ibc_application_id" INTEGER NOT NULL,
  "research_activity_id" INTEGER NOT NULL,
  "created_at" TEXT
);

-- ibcApplicationRooms
CREATE TABLE IF NOT EXISTS "ibc_application_rooms" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "application_id" INTEGER NOT NULL,
  "room_id" INTEGER NOT NULL,
  "created_at" TEXT
);

-- ibcApplications
CREATE TABLE IF NOT EXISTS "ibc_applications" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "ibc_number" TEXT NOT NULL,
  "cayuse_protocol_number" TEXT,
  "irbnet_ibc_number" TEXT,
  "title" TEXT NOT NULL,
  "short_title" TEXT,
  "principal_investigator_id" INTEGER NOT NULL,
  "additional_notification_email" TEXT,
  "biosafety_level" TEXT NOT NULL,
  "risk_group_classification" TEXT,
  "recombinant_synthetic_nucleic_acid" INTEGER DEFAULT 0,
  "whole_animals_animal_material" INTEGER DEFAULT 0,
  "animal_material_sub_options" TEXT,
  "human_non_human_primate_material" INTEGER DEFAULT 0,
  "introducing_primate_material_into_animals" INTEGER,
  "microorganisms_infectious_material" INTEGER DEFAULT 0,
  "introducing_recombinant_dna_to_microorganisms" INTEGER,
  "biological_toxins" INTEGER DEFAULT 0,
  "nanoparticles" INTEGER DEFAULT 0,
  "arthropods" INTEGER DEFAULT 0,
  "transgenic_arthropods_or_exposure" INTEGER,
  "plants" INTEGER DEFAULT 0,
  "transgenic_plants_or_exposure" INTEGER,
  "human_origin" INTEGER DEFAULT 0,
  "human_materials" TEXT,
  "human_materials_tissues_other" TEXT,
  "human_materials_other_material" TEXT,
  "non_human_primate_origin" INTEGER DEFAULT 0,
  "nhp_exposure_kit" INTEGER,
  "stem_cells" TEXT,
  "stem_cells_nih_registry" INTEGER,
  "exposure_control_plan_compliance" INTEGER DEFAULT 0,
  "hand_washing_device" INTEGER DEFAULT 0,
  "laundry_method" TEXT,
  "laundry_method_other" TEXT,
  "materials_contain_known_pathogens" INTEGER DEFAULT 0,
  "material_pathogen_details" TEXT,
  "material_treatment_details" TEXT,
  "infection_symptoms" TEXT,
  "biological_agents" TEXT,
  "chemical_agents" TEXT,
  "radiological_materials" TEXT,
  "recombinant_dna" INTEGER DEFAULT 0,
  "animal_work" INTEGER DEFAULT 0,
  "field_work" INTEGER DEFAULT 0,
  "using_recombinant_dna_detection" INTEGER DEFAULT 0,
  "creating_genomic_libraries" INTEGER DEFAULT 0,
  "cloning_vector_construction" INTEGER DEFAULT 0,
  "expression_cultured_cells" INTEGER DEFAULT 0,
  "use_human_cell_lines" INTEGER DEFAULT 0,
  "use_animal_cell_lines" INTEGER DEFAULT 0,
  "use_stem_cells" INTEGER DEFAULT 0,
  "risk_group_2_3_genes" INTEGER DEFAULT 0,
  "administering_to_animals" INTEGER DEFAULT 0,
  "large_culture_volumes" INTEGER DEFAULT 0,
  "infectious_virus_work" INTEGER DEFAULT 0,
  "toxin_genes" INTEGER DEFAULT 0,
  "approved_rooms" TEXT,
  "lab_policies_compliance" TEXT,
  "disinfection_methods" TEXT,
  "waste_sterilization_methods" TEXT,
  "required_ppe" TEXT,
  "hazard_assessment" TEXT,
  "safety_controls" TEXT,
  "additional_recommended_controls" TEXT,
  "iacuc_protocol_number" TEXT,
  "irb_protocol_number" TEXT,
  "medical_surveillance" INTEGER DEFAULT 0,
  "submission_date" TEXT,
  "vetted_date" TEXT,
  "under_review_date" TEXT,
  "approval_date" TEXT,
  "expiration_date" TEXT,
  "last_review_date" TEXT,
  "next_review_date" TEXT,
  "status" TEXT NOT NULL,
  "workflow_status" TEXT NOT NULL DEFAULT 'draft',
  "submission_type" TEXT NOT NULL DEFAULT 'initial',
  "version" INTEGER NOT NULL DEFAULT 1,
  "risk_level" TEXT NOT NULL,
  "requires_monitoring" INTEGER DEFAULT 0,
  "monitoring_frequency" TEXT,
  "reporting_requirements" TEXT,
  "reviewer_assignments" TEXT,
  "review_comments" TEXT,
  "pi_responses" TEXT,
  "protocol_team_members" TEXT,
  "description" TEXT,
  "protocol_summary" TEXT,
  "nih_section_abc" TEXT,
  "nih_section_d" TEXT,
  "nih_section_e" TEXT,
  "nih_section_f" TEXT,
  "nih_appendix_c" TEXT,
  "cell_lines" TEXT,
  "hazardous_procedures" TEXT,
  "synthetic_experiments" TEXT,
  "proposed_biosafety_levels" TEXT,
  "host_organism_dna_propagation" TEXT,
  "purification_measures" TEXT,
  "provided_restriction_vector_maps" INTEGER,
  "viral_genome_regions_altered" TEXT,
  "assaying_wild_type_viral" INTEGER,
  "deviating_from_local_transport" INTEGER,
  "deviating_from_local_transport_details" TEXT,
  "transporting_bio_hazardous_to_off_campus" INTEGER,
  "transporting_bio_hazardous_to_off_campus_details" TEXT,
  "receiving_biological_from_off_campus" INTEGER,
  "dual_use_agents_and_toxins" TEXT,
  "dual_use_categories_apply" INTEGER,
  "dual_use_categories_explanation" TEXT,
  "dual_use_experiment_categories" TEXT,
  "handle_more_than_10_liters" INTEGER,
  "gene_drive_system_crispr" INTEGER,
  "documents" TEXT,
  "form_data" TEXT,
  "inactivation_decontamination" TEXT,
  "disposal" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  CONSTRAINT "ibc_applications_ibc_number_unique" UNIQUE ("ibc_number")
);

-- ibcBackboneSourceRooms
CREATE TABLE IF NOT EXISTS "ibc_backbone_source_rooms" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "application_id" INTEGER NOT NULL,
  "backbone_source" TEXT NOT NULL,
  "room_id" INTEGER NOT NULL,
  "created_at" TEXT
);

-- ibcBoardMembers
CREATE TABLE IF NOT EXISTS "ibc_board_members" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "scientist_id" INTEGER NOT NULL,
  "role" TEXT NOT NULL,
  "expertise" TEXT,
  "biosafety_training" TEXT,
  "appointment_date" TEXT,
  "term_end_date" TEXT NOT NULL,
  "is_active" INTEGER DEFAULT 1,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- ibcDocuments
CREATE TABLE IF NOT EXISTS "ibc_documents" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "application_id" INTEGER,
  "submission_id" INTEGER,
  "document_type" TEXT NOT NULL,
  "file_name" TEXT NOT NULL,
  "file_size" INTEGER,
  "mime_type" TEXT,
  "uploaded_by" INTEGER NOT NULL,
  "upload_date" TEXT,
  "version" INTEGER NOT NULL DEFAULT 1,
  "is_current_version" INTEGER DEFAULT 1,
  "review_status" TEXT DEFAULT 'pending',
  "review_comments" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- ibcSubmissions
CREATE TABLE IF NOT EXISTS "ibc_submissions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "application_id" INTEGER NOT NULL,
  "submission_type" TEXT NOT NULL,
  "submission_date" TEXT,
  "submitted_by" INTEGER NOT NULL,
  "documents" TEXT,
  "review_status" TEXT NOT NULL DEFAULT 'pending',
  "review_date" TEXT,
  "reviewed_by" INTEGER,
  "review_comments" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- irbApplications
CREATE TABLE IF NOT EXISTS "irb_applications" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "research_activity_id" INTEGER,
  "irb_number" TEXT NOT NULL,
  "irb_net_number" TEXT,
  "old_number" TEXT,
  "title" TEXT NOT NULL,
  "short_title" TEXT,
  "principal_investigator_id" INTEGER NOT NULL,
  "additional_notification_email" TEXT,
  "protocol_type" TEXT,
  "is_interventional" INTEGER DEFAULT 0,
  "submission_date" TEXT,
  "initial_approval_date" TEXT,
  "expiration_date" TEXT,
  "status" TEXT NOT NULL,
  "subject_enrollment_reasons" TEXT,
  "description" TEXT,
  "documents" TEXT,
  "workflow_status" TEXT NOT NULL DEFAULT 'draft',
  "submission_type" TEXT DEFAULT 'initial',
  "version" INTEGER DEFAULT 1,
  "form_data" TEXT,
  "risk_level" TEXT,
  "vulnerable_populations" TEXT,
  "study_design" TEXT,
  "data_collection_methods" TEXT,
  "expected_participants" INTEGER,
  "study_duration" TEXT,
  "funding_source" TEXT,
  "conflict_of_interest" INTEGER DEFAULT 0,
  "multi_site" INTEGER DEFAULT 0,
  "international_sites" INTEGER DEFAULT 0,
  "reviewer_assignments" TEXT,
  "review_comments" TEXT,
  "pi_responses" TEXT,
  "requires_monitoring" INTEGER DEFAULT 0,
  "monitoring_frequency" TEXT,
  "reporting_requirements" TEXT,
  "protocol_team_members" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  CONSTRAINT "irb_applications_irb_number_unique" UNIQUE ("irb_number")
);

-- irbBoardMembers
CREATE TABLE IF NOT EXISTS "irb_board_members" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "scientist_id" INTEGER NOT NULL,
  "role" TEXT NOT NULL,
  "expertise" TEXT,
  "appointment_date" TEXT,
  "term_end_date" TEXT NOT NULL,
  "is_active" INTEGER DEFAULT 1,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- irbDocuments
CREATE TABLE IF NOT EXISTS "irb_documents" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "application_id" INTEGER,
  "submission_id" INTEGER,
  "document_type" TEXT NOT NULL,
  "file_name" TEXT NOT NULL,
  "file_path" TEXT NOT NULL,
  "file_size" INTEGER,
  "mime_type" TEXT,
  "version" INTEGER DEFAULT 1,
  "uploaded_by" INTEGER NOT NULL,
  "is_required" INTEGER DEFAULT 0,
  "status" TEXT DEFAULT 'active',
  "created_at" TEXT,
  "updated_at" TEXT
);

-- irbSubmissions
CREATE TABLE IF NOT EXISTS "irb_submissions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "application_id" INTEGER NOT NULL,
  "submission_type" TEXT NOT NULL,
  "version" INTEGER NOT NULL DEFAULT 1,
  "submitted_by" INTEGER NOT NULL,
  "submission_date" TEXT,
  "due_date" TEXT,
  "form_data" TEXT,
  "changes" TEXT,
  "documents" TEXT,
  "workflow_status" TEXT NOT NULL DEFAULT 'submitted',
  "reviewer_assignments" TEXT,
  "review_comments" TEXT,
  "pi_responses" TEXT,
  "final_decision" TEXT,
  "decision_date" TEXT,
  "decision_rationale" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- journalImpactFactorMetrics
CREATE TABLE IF NOT EXISTS "journal_impact_factor_metrics" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "journal_id" INTEGER NOT NULL,
  "year" INTEGER NOT NULL,
  "total_cites" INTEGER,
  "total_articles" INTEGER,
  "citable_items" INTEGER,
  "cited_half_life" REAL,
  "citing_half_life" REAL,
  "impact_factor" REAL,
  "five_year_jif" REAL,
  "jif_without_self_cites" REAL,
  "jci" REAL,
  "quartile" TEXT,
  "rank" INTEGER,
  "total_citations" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- journals
CREATE TABLE IF NOT EXISTS "journals" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "journal_name" TEXT NOT NULL,
  "abbreviated_journal" TEXT,
  "publisher" TEXT,
  "issn" TEXT,
  "eissn" TEXT,
  "field" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- manuscriptHistory
CREATE TABLE IF NOT EXISTS "manuscript_history" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "publication_id" INTEGER NOT NULL,
  "from_status" TEXT,
  "to_status" TEXT NOT NULL,
  "changed_field" TEXT,
  "old_value" TEXT,
  "new_value" TEXT,
  "changed_by" INTEGER NOT NULL,
  "change_reason" TEXT,
  "created_at" TEXT
);

-- ownershipOverrides
CREATE TABLE IF NOT EXISTS "ownership_overrides" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "module" TEXT NOT NULL,
  "relationship" TEXT NOT NULL,
  "granted_access" TEXT NOT NULL,
  "description" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- patents
CREATE TABLE IF NOT EXISTS "patents" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "research_activity_id" INTEGER,
  "title" TEXT NOT NULL,
  "inventors" TEXT NOT NULL,
  "filing_date" TEXT,
  "grant_date" TEXT,
  "patent_number" TEXT,
  "status" TEXT NOT NULL,
  "description" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- pdfImportHistory
CREATE TABLE IF NOT EXISTS "pdf_import_history" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "file_name" TEXT NOT NULL,
  "file_url" TEXT NOT NULL,
  "file_size" INTEGER,
  "uploaded_by" INTEGER NOT NULL,
  "processing_status" TEXT NOT NULL DEFAULT 'processing',
  "ocr_provider" TEXT,
  "document_type" TEXT,
  "extracted_text" TEXT,
  "parsed_data" TEXT,
  "error_message" TEXT,
  "processing_duration" INTEGER,
  "save_status" TEXT,
  "certificate_person_name" TEXT,
  "course_name" TEXT,
  "completion_date" TEXT,
  "expiration_date" TEXT,
  "record_id" TEXT,
  "institution" TEXT,
  "assigned_scientist_id" INTEGER,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- programs
CREATE TABLE IF NOT EXISTS "programs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "program_id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "program_director_id" INTEGER,
  "research_co_lead_id" INTEGER,
  "clinical_co_lead_1_id" INTEGER,
  "clinical_co_lead_2_id" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT,
  CONSTRAINT "programs_program_id_unique" UNIQUE ("program_id")
);

-- projectMembers
CREATE TABLE IF NOT EXISTS "project_members" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "research_activity_id" INTEGER NOT NULL,
  "scientist_id" INTEGER NOT NULL,
  "role" TEXT
);

-- projects
CREATE TABLE IF NOT EXISTS "projects" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "project_id" TEXT NOT NULL,
  "program_id" INTEGER,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "principal_investigator_id" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT,
  CONSTRAINT "projects_project_id_unique" UNIQUE ("project_id")
);

-- publicationAuthors
CREATE TABLE IF NOT EXISTS "publication_authors" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "publication_id" INTEGER NOT NULL,
  "scientist_id" INTEGER NOT NULL,
  "authorship_type" TEXT NOT NULL,
  "author_position" INTEGER,
  "linked_by_user_id" INTEGER,
  "link_method" TEXT NOT NULL DEFAULT 'manual'
);

-- publications
CREATE TABLE IF NOT EXISTS "publications" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "research_activity_id" INTEGER,
  "title" TEXT NOT NULL,
  "abstract" TEXT,
  "authors" TEXT,
  "journal" TEXT,
  "volume" TEXT,
  "issue" TEXT,
  "pages" TEXT,
  "doi" TEXT,
  "pmid" TEXT,
  "publication_date" TEXT,
  "publication_type" TEXT,
  "status" TEXT DEFAULT 'Concept',
  "invalid_reason" TEXT,
  "vetted_for_submission_by_ip_office" INTEGER DEFAULT 0,
  "prepublication_url" TEXT,
  "prepublication_site" TEXT,
  "alternate_dois" TEXT,
  "created_by_user_id" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- ra200Applications
CREATE TABLE IF NOT EXISTS "ra200_applications" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "application_id" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'draft',
  "title" TEXT NOT NULL,
  "lead_scientist_id" INTEGER,
  "project_id" INTEGER,
  "budget_holder_id" INTEGER,
  "budget_source" TEXT,
  "abstract" TEXT,
  "background_rationale" TEXT,
  "objectives_preliminary" TEXT,
  "approach_methods" TEXT,
  "discussion_conclusion" TEXT,
  "ethics_requirements" TEXT,
  "collaboration_requirements" TEXT,
  "budget_requirements" TEXT,
  "sample_data_processing" TEXT,
  "duration_months" INTEGER,
  "core_labs" TEXT,
  "study_design_methods" TEXT,
  "proposal_objectives" TEXT,
  "preliminary_data" TEXT,
  "submitted_by" INTEGER,
  "office_comments" TEXT DEFAULT '[]',
  "pi_comments" TEXT DEFAULT '[]',
  "review_history" TEXT DEFAULT '[]',
  "created_at" TEXT,
  "updated_at" TEXT,
  CONSTRAINT "ra200_applications_application_id_unique" UNIQUE ("application_id")
);

-- ra205aApplications
CREATE TABLE IF NOT EXISTS "ra205a_applications" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "application_id" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'draft',
  "title" TEXT NOT NULL,
  "lead_scientist_id" INTEGER,
  "project_id" INTEGER,
  "budget_holder_id" INTEGER,
  "budget_source" TEXT,
  "sdr_number" TEXT,
  "current_title" TEXT,
  "activity_type" TEXT,
  "change_category" TEXT,
  "change_reason" TEXT,
  "change_request_number" TEXT,
  "current_pi_id" INTEGER,
  "new_pi_id" INTEGER,
  "current_pi_signature" TEXT,
  "new_pi_signature" TEXT,
  "stakeholder_certifications" TEXT,
  "submitted_by" INTEGER,
  "office_comments" TEXT DEFAULT '[]',
  "pi_comments" TEXT DEFAULT '[]',
  "review_history" TEXT DEFAULT '[]',
  "created_at" TEXT,
  "updated_at" TEXT,
  CONSTRAINT "ra205a_applications_application_id_unique" UNIQUE ("application_id")
);

-- researchActivities
CREATE TABLE IF NOT EXISTS "research_activities" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "sdr_number" TEXT NOT NULL,
  "project_id" INTEGER,
  "title" TEXT NOT NULL,
  "short_title" TEXT,
  "description" TEXT,
  "status" TEXT NOT NULL DEFAULT 'planning',
  "start_date" TEXT,
  "end_date" TEXT,
  "budget_holder_id" INTEGER,
  "line_manager_id" INTEGER,
  "additional_notification_email" TEXT,
  "sidra_branch" TEXT,
  "budget_source" TEXT,
  "objectives" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  "staff_scientist_id" INTEGER,
  "grant_codes" TEXT,
  CONSTRAINT "research_activities_sdr_number_unique" UNIQUE ("sdr_number")
);

-- researchContractDocuments
CREATE TABLE IF NOT EXISTS "research_contract_documents" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "contract_id" INTEGER,
  "extension_id" INTEGER,
  "document_type" TEXT NOT NULL,
  "object_key" TEXT NOT NULL,
  "file_name" TEXT NOT NULL,
  "mime_type" TEXT,
  "file_size" INTEGER,
  "uploaded_by_user_id" INTEGER NOT NULL,
  "uploaded_at" TEXT,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- researchContractExtensions
CREATE TABLE IF NOT EXISTS "research_contract_extensions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "contract_id" INTEGER NOT NULL,
  "sequence_number" INTEGER NOT NULL,
  "requested_at" TEXT,
  "approved_at" TEXT,
  "new_end_date" TEXT NOT NULL,
  "signature_date" TEXT,
  "notes" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- researchContractScopeItems
CREATE TABLE IF NOT EXISTS "research_contract_scope_items" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "contract_id" INTEGER NOT NULL,
  "party" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "due_date" TEXT,
  "acceptance_criteria" TEXT,
  "position" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- researchContracts
CREATE TABLE IF NOT EXISTS "research_contracts" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "research_activity_id" INTEGER,
  "contract_number" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "lead_pi_id" INTEGER,
  "irb_protocol" TEXT,
  "ibc_protocol" TEXT,
  "qnrf_number" TEXT,
  "request_state" TEXT,
  "start_date" TEXT,
  "end_date" TEXT,
  "remarks" TEXT,
  "funding_source_category" TEXT,
  "contractor_name" TEXT,
  "counterparty_contact" TEXT,
  "counterparty_country" TEXT,
  "internal_cost_sidra" INTEGER,
  "internal_cost_counterparty" INTEGER,
  "money_out" INTEGER,
  "is_po_relevant" INTEGER DEFAULT 0,
  "contract_type" TEXT,
  "status" TEXT NOT NULL DEFAULT 'submitted',
  "description" TEXT,
  "documents" TEXT,
  "requested_by_user_id" INTEGER,
  "contract_value" REAL,
  "currency" TEXT DEFAULT 'QAR',
  "initiation_requested_at" TEXT,
  "reminder_email" TEXT,
  "office_form_status" TEXT DEFAULT 'incomplete',
  "created_at" TEXT,
  "updated_at" TEXT,
  CONSTRAINT "research_contracts_contract_number_unique" UNIQUE ("contract_number")
);

-- roleGroups
CREATE TABLE IF NOT EXISTS "role_groups" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "name" TEXT NOT NULL,
  "description" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  CONSTRAINT "role_groups_name_unique" UNIQUE ("name")
);

-- rolePermissions
CREATE TABLE IF NOT EXISTS "role_permissions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "role_group_id" INTEGER NOT NULL,
  "navigation_item" TEXT NOT NULL,
  "access_level" TEXT NOT NULL,
  "updated_by" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- rooms
CREATE TABLE IF NOT EXISTS "rooms" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "buildingId" INTEGER NOT NULL,
  "roomNumber" TEXT NOT NULL,
  "floor" INTEGER,
  "roomType" TEXT,
  "capacity" INTEGER,
  "area" REAL,
  "biosafetyLevel" TEXT,
  "roomSupervisorId" INTEGER,
  "roomManagerId" INTEGER,
  "certifications" TEXT,
  "availablePpe" TEXT,
  "equipment" TEXT,
  "specialFeatures" TEXT,
  "accessRestrictions" TEXT,
  "maintenanceNotes" TEXT
);

-- scientists
CREATE TABLE IF NOT EXISTS "scientists" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "honorific_title" TEXT NOT NULL,
  "first_name" TEXT NOT NULL,
  "last_name" TEXT NOT NULL,
  "job_title" TEXT,
  "is_investigator" INTEGER NOT NULL DEFAULT 0,
  "email" TEXT NOT NULL,
  "staff_id" TEXT,
  "department" TEXT,
  "department_id" INTEGER,
  "section_id" INTEGER,
  "bio" TEXT,
  "profile_image_initials" TEXT,
  "supervisor_id" INTEGER,
  "staff_type" TEXT NOT NULL DEFAULT 'scientific',
  "orcid_id" TEXT,
  "linkedin_url" TEXT,
  "google_scholar_url" TEXT,
  "web_of_science_id" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  CONSTRAINT "scientists_email_unique" UNIQUE ("email"),
  CONSTRAINT "scientists_staff_id_unique" UNIQUE ("staff_id")
);

-- sections
CREATE TABLE IF NOT EXISTS "sections" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "department_id" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "description" TEXT,
  "head_id" INTEGER,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- systemConfigurations
CREATE TABLE IF NOT EXISTS "system_configurations" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "key" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  "description" TEXT,
  "category" TEXT NOT NULL DEFAULT 'general',
  "is_user_configurable" INTEGER NOT NULL DEFAULT 1,
  "created_at" TEXT,
  "updated_at" TEXT,
  CONSTRAINT "system_configurations_key_unique" UNIQUE ("key")
);

-- teamMembers
CREATE TABLE IF NOT EXISTS "team_members" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "first_name" TEXT NOT NULL,
  "last_name" TEXT NOT NULL,
  "title" TEXT,
  "bio" TEXT,
  "photo_url" TEXT,
  "categories" TEXT NOT NULL,
  "element_type" TEXT,
  "institution" TEXT,
  "email" TEXT,
  "linkedin_url" TEXT,
  "display_order" INTEGER DEFAULT 0,
  "is_active" INTEGER DEFAULT 1,
  "created_at" TEXT,
  "updated_at" TEXT
);

-- userRoleAssignments
CREATE TABLE IF NOT EXISTS "user_role_assignments" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "user_id" INTEGER NOT NULL,
  "role_group_id" INTEGER NOT NULL,
  "assigned_by" INTEGER,
  "assigned_at" TEXT
);

-- users
CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "username" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "role" TEXT NOT NULL DEFAULT 'user',
  "auth_provider" TEXT NOT NULL DEFAULT 'local',
  "entra_oid" TEXT,
  "scientist_id" INTEGER,
  "last_login_at" TEXT,
  "created_at" TEXT,
  "updated_at" TEXT,
  CONSTRAINT "users_username_unique" UNIQUE ("username"),
  CONSTRAINT "users_entra_oid_unique" UNIQUE ("entra_oid")
);
